### ISSUE TITLE
environment__*_variables lists versus dicts?

### ISSUE THREAD

**Issue by phillbaker** [debops/ansible-environment#2]
Thanks for all the hard work on debops! I can move this question to IRC or the mailing list, but thought I'd start here.

I was looking for any information on why the `environment__*_variables` are stored as lists of key value pairs, rather than dicts? Since ansible itself specifies environment variables as dicts for a playbook, trying to re-use groups of data between the two is much harder when having to convert between list and dict.

**Comment by drybjed** [comment]
First of all, [as per the examples in the documentation](https://docs.debops.org/en/latest/ansible/roles/ansible-environment/docs/defaults-detailed.html#environment-variables), you can specify environment variables in the YAML dict format inside a list:
```
environment__variables:
  - variable1: 'value1'
    variable2: 'value2'
```
As for why they are specified as a list in the first place - this allows to have the expanded form of a variable which can be enabled conditionally on a host if needed. If variables were only defined as YAML dicts, you wouldn't be able to do that. Well, you could but with a more intricate templating. Which I might do in the future, we'll see.

**Comment by phillbaker** [comment]
I completely missed that, thanks!
